//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference3
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BilesikKutukSorgulaKimlikNoSorguKriteri", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class BilesikKutukSorgulaKimlikNoSorguKriteri : object
    {
        
        private System.Nullable<int> DogumAyField;
        
        private System.Nullable<int> DogumGunField;
        
        private System.Nullable<int> DogumYilField;
        
        private System.Nullable<long> KimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumAy
        {
            get
            {
                return this.DogumAyField;
            }
            set
            {
                this.DogumAyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumGun
        {
            get
            {
                return this.DogumGunField;
            }
            set
            {
                this.DogumGunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYil
        {
            get
            {
                return this.DogumYilField;
            }
            set
            {
                this.DogumYilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BilesikKutukBilgileriSonucu", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class BilesikKutukBilgileriSonucu : object
    {
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.BilesikKutukBilgileri[] SorguSonucuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.BilesikKutukBilgileri[] SorguSonucu
        {
            get
            {
                return this.SorguSonucuField;
            }
            set
            {
                this.SorguSonucuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class Parametre : object
    {
        
        private string AciklamaField;
        
        private System.Nullable<int> KodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BilesikKutukBilgileri", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class BilesikKutukBilgileri : object
    {
        
        private ServiceReference3.CstBilesikKutukServisDoluBilesen[] DoluBilesenlerField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference3.MaviKartKisiKutukleri MaviKartliKisiKutukleriField;
        
        private ServiceReference3.TCVatandasiKisiKutukleri TCVatandasiKisiKutukleriField;
        
        private ServiceReference3.YabanciKisiKutukleri YabanciKisiKutukleriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.CstBilesikKutukServisDoluBilesen[] DoluBilesenler
        {
            get
            {
                return this.DoluBilesenlerField;
            }
            set
            {
                this.DoluBilesenlerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.MaviKartKisiKutukleri MaviKartliKisiKutukleri
        {
            get
            {
                return this.MaviKartliKisiKutukleriField;
            }
            set
            {
                this.MaviKartliKisiKutukleriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCVatandasiKisiKutukleri TCVatandasiKisiKutukleri
        {
            get
            {
                return this.TCVatandasiKisiKutukleriField;
            }
            set
            {
                this.TCVatandasiKisiKutukleriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YabanciKisiKutukleri YabanciKisiKutukleri
        {
            get
            {
                return this.YabanciKisiKutukleriField;
            }
            set
            {
                this.YabanciKisiKutukleriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviKartKisiKutukleri", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class MaviKartKisiKutukleri : object
    {
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.MaviKartKisiBilgisi KisiBilgisiField;
        
        private ServiceReference3.MaviKartBilgi MaviKartBilgisiField;
        
        private ServiceReference3.YeniMaviKartBilgi YeniMaviKartBilgisiField;
        
        private ServiceReference3.YeniMaviFotoBilgi YeniMaviKartFotoBilgisiField;
        
        private ServiceReference3.YeniMaviKartGeciciKimlikBilgi YeniMaviKartGeciciKimlikBilgisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.MaviKartKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.KisiBilgisiField;
            }
            set
            {
                this.KisiBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.MaviKartBilgi MaviKartBilgisi
        {
            get
            {
                return this.MaviKartBilgisiField;
            }
            set
            {
                this.MaviKartBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YeniMaviKartBilgi YeniMaviKartBilgisi
        {
            get
            {
                return this.YeniMaviKartBilgisiField;
            }
            set
            {
                this.YeniMaviKartBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YeniMaviFotoBilgi YeniMaviKartFotoBilgisi
        {
            get
            {
                return this.YeniMaviKartFotoBilgisiField;
            }
            set
            {
                this.YeniMaviKartFotoBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YeniMaviKartGeciciKimlikBilgi YeniMaviKartGeciciKimlikBilgisi
        {
            get
            {
                return this.YeniMaviKartGeciciKimlikBilgisiField;
            }
            set
            {
                this.YeniMaviKartGeciciKimlikBilgisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCVatandasiKisiKutukleri", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCVatandasiKisiKutukleri : object
    {
        
        private ServiceReference3.TCGeciciKimlikBilgisi GeciciKimlikBilgisiField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.TCKisiBilgisi KisiBilgisiField;
        
        private ServiceReference3.TCCuzdanBilgisi NufusCuzdaniBilgisiField;
        
        private ServiceReference3.TCKK TCKKBilgisiField;
        
        private ServiceReference3.TCKKFotoBilgisi TCKKFotografBilgisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCGeciciKimlikBilgisi GeciciKimlikBilgisi
        {
            get
            {
                return this.GeciciKimlikBilgisiField;
            }
            set
            {
                this.GeciciKimlikBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.KisiBilgisiField;
            }
            set
            {
                this.KisiBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCCuzdanBilgisi NufusCuzdaniBilgisi
        {
            get
            {
                return this.NufusCuzdaniBilgisiField;
            }
            set
            {
                this.NufusCuzdaniBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCKK TCKKBilgisi
        {
            get
            {
                return this.TCKKBilgisiField;
            }
            set
            {
                this.TCKKBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCKKFotoBilgisi TCKKFotografBilgisi
        {
            get
            {
                return this.TCKKFotografBilgisiField;
            }
            set
            {
                this.TCKKFotografBilgisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YabanciKisiKutukleri", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YabanciKisiKutukleri : object
    {
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.YabanciKisiBilgisi KisiBilgisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YabanciKisiBilgisi KisiBilgisi
        {
            get
            {
                return this.KisiBilgisiField;
            }
            set
            {
                this.KisiBilgisiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CstBilesikKutukServisDoluBilesen", Namespace="http://schemas.datacontract.org/2004/07/Common.Types.Constants")]
    public enum CstBilesikKutukServisDoluBilesen : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCKisiBilgisi = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCKKGeciciKimlikBilgisi = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCKKBilgisi = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TCKKFotoBilgisi = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NufusCuzdaniBilgisi = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaviKartliKisiBilgisi = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaviKartBilgisi = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YabanciKisiBilgisi = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YeniMaviKartGeciciKimlikBilgisi = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YeniMaviKartBilgisi = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YeniMaviKartFotoBilgisi = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviKartKisiBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class MaviKartKisiBilgisi : object
    {
        
        private System.Nullable<long> AnneTCKimlikNoField;
        
        private System.Nullable<long> BabaTCKimlikNoField;
        
        private System.Nullable<int> DogumYerKodField;
        
        private ServiceReference3.MaviKartKisiDurumBilgisi DurumBilgisiField;
        
        private System.Nullable<long> EsTCKimlikNoField;
        
        private System.Nullable<long> GercekKisiKimlikNoField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KazanilanTCKimlikNoField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference3.MaviKartKisiTemelBilgisi TemelBilgisiField;
        
        private ServiceReference3.Parametre UlkeField;
        
        private ServiceReference3.Parametre VeliVasiTurField;
        
        private System.Nullable<bool> VeliVasiVarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneTCKimlikNo
        {
            get
            {
                return this.AnneTCKimlikNoField;
            }
            set
            {
                this.AnneTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaTCKimlikNo
        {
            get
            {
                return this.BabaTCKimlikNoField;
            }
            set
            {
                this.BabaTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.DogumYerKodField;
            }
            set
            {
                this.DogumYerKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.MaviKartKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.DurumBilgisiField;
            }
            set
            {
                this.DurumBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsTCKimlikNo
        {
            get
            {
                return this.EsTCKimlikNoField;
            }
            set
            {
                this.EsTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GercekKisiKimlikNo
        {
            get
            {
                return this.GercekKisiKimlikNoField;
            }
            set
            {
                this.GercekKisiKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KazanilanTCKimlikNo
        {
            get
            {
                return this.KazanilanTCKimlikNoField;
            }
            set
            {
                this.KazanilanTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.MaviKartKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.TemelBilgisiField;
            }
            set
            {
                this.TemelBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Ulke
        {
            get
            {
                return this.UlkeField;
            }
            set
            {
                this.UlkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre VeliVasiTur
        {
            get
            {
                return this.VeliVasiTurField;
            }
            set
            {
                this.VeliVasiTurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> VeliVasiVar
        {
            get
            {
                return this.VeliVasiVarField;
            }
            set
            {
                this.VeliVasiVarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviKartBilgi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class MaviKartBilgi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private System.Nullable<int> BirimField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private string DogumYerField;
        
        private System.Nullable<int> DogumYerKodField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KartKayitNoField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference3.Parametre MedeniHalField;
        
        private System.Nullable<int> NoField;
        
        private string OncekiSoyadField;
        
        private string SeriField;
        
        private string SoyadField;
        
        private ServiceReference3.Parametre UyrukField;
        
        private ServiceReference3.Parametre VerilisNedenField;
        
        private ServiceReference3.TarihBilgisi VerilmeTarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Birim
        {
            get
            {
                return this.BirimField;
            }
            set
            {
                this.BirimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.DogumYerKodField;
            }
            set
            {
                this.DogumYerKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KartKayitNo
        {
            get
            {
                return this.KartKayitNoField;
            }
            set
            {
                this.KartKayitNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre MedeniHal
        {
            get
            {
                return this.MedeniHalField;
            }
            set
            {
                this.MedeniHalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> No
        {
            get
            {
                return this.NoField;
            }
            set
            {
                this.NoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OncekiSoyad
        {
            get
            {
                return this.OncekiSoyadField;
            }
            set
            {
                this.OncekiSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seri
        {
            get
            {
                return this.SeriField;
            }
            set
            {
                this.SeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre VerilisNeden
        {
            get
            {
                return this.VerilisNedenField;
            }
            set
            {
                this.VerilisNedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi VerilmeTarih
        {
            get
            {
                return this.VerilmeTarihField;
            }
            set
            {
                this.VerilmeTarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YeniMaviKartBilgi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YeniMaviKartBilgi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KimlikNoField;
        
        private string SeriNoField;
        
        private ServiceReference3.TarihBilgisi SonGecerlilikTarihField;
        
        private string SoyadField;
        
        private ServiceReference3.Parametre UyrukField;
        
        private string VerenMakamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeriNo
        {
            get
            {
                return this.SeriNoField;
            }
            set
            {
                this.SeriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.SonGecerlilikTarihField;
            }
            set
            {
                this.SonGecerlilikTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerenMakam
        {
            get
            {
                return this.VerenMakamField;
            }
            set
            {
                this.VerenMakamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YeniMaviFotoBilgi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YeniMaviFotoBilgi : object
    {
        
        private byte[] FotografField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotograf
        {
            get
            {
                return this.FotografField;
            }
            set
            {
                this.FotografField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YeniMaviKartGeciciKimlikBilgi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YeniMaviKartGeciciKimlikBilgi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private string BelgeNoField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private ServiceReference3.TarihBilgisi DuzenlenmeTarihField;
        
        private ServiceReference3.Parametre DuzenleyenIlceField;
        
        private byte[] FotografField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference3.TarihBilgisi SonGecerlilikTarihField;
        
        private string SoyadField;
        
        private ServiceReference3.Parametre UyrukField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelgeNo
        {
            get
            {
                return this.BelgeNoField;
            }
            set
            {
                this.BelgeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DuzenlenmeTarih
        {
            get
            {
                return this.DuzenlenmeTarihField;
            }
            set
            {
                this.DuzenlenmeTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre DuzenleyenIlce
        {
            get
            {
                return this.DuzenleyenIlceField;
            }
            set
            {
                this.DuzenleyenIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotograf
        {
            get
            {
                return this.FotografField;
            }
            set
            {
                this.FotografField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.SonGecerlilikTarihField;
            }
            set
            {
                this.SonGecerlilikTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviKartKisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class MaviKartKisiDurumBilgisi : object
    {
        
        private ServiceReference3.Parametre DurumField;
        
        private ServiceReference3.Parametre MedeniHalField;
        
        private ServiceReference3.TarihBilgisi OlumTarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre MedeniHal
        {
            get
            {
                return this.MedeniHalField;
            }
            set
            {
                this.MedeniHalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi OlumTarih
        {
            get
            {
                return this.OlumTarihField;
            }
            set
            {
                this.OlumTarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaviKartKisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class MaviKartKisiTemelBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private string DogumYerField;
        
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class TarihBilgisi : object
    {
        
        private System.Nullable<int> AyField;
        
        private System.Nullable<int> GunField;
        
        private System.Nullable<int> YilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.AyField;
            }
            set
            {
                this.AyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.GunField;
            }
            set
            {
                this.GunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.YilField;
            }
            set
            {
                this.YilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCGeciciKimlikBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCGeciciKimlikBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private string BelgeNoField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private ServiceReference3.TarihBilgisi DuzenlenmeTarihField;
        
        private ServiceReference3.Parametre DuzenleyenIlceField;
        
        private byte[] FotografField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.Parametre KanGrubuField;
        
        private string OncekiSoyadField;
        
        private ServiceReference3.TarihBilgisi SonGecerlilikTarihField;
        
        private string SoyadField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BelgeNo
        {
            get
            {
                return this.BelgeNoField;
            }
            set
            {
                this.BelgeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DuzenlenmeTarih
        {
            get
            {
                return this.DuzenlenmeTarihField;
            }
            set
            {
                this.DuzenlenmeTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre DuzenleyenIlce
        {
            get
            {
                return this.DuzenleyenIlceField;
            }
            set
            {
                this.DuzenleyenIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotograf
        {
            get
            {
                return this.FotografField;
            }
            set
            {
                this.FotografField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre KanGrubu
        {
            get
            {
                return this.KanGrubuField;
            }
            set
            {
                this.KanGrubuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OncekiSoyad
        {
            get
            {
                return this.OncekiSoyadField;
            }
            set
            {
                this.OncekiSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.SonGecerlilikTarihField;
            }
            set
            {
                this.SonGecerlilikTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKisiBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCKisiBilgisi : object
    {
        
        private System.Nullable<long> AnneTCKimlikNoField;
        
        private System.Nullable<bool> AnneUstSoyBulunamadiField;
        
        private System.Nullable<long> BabaTCKimlikNoField;
        
        private System.Nullable<bool> BabaUstSoyBulunamadiField;
        
        private System.Nullable<int> DogumYerKodField;
        
        private ServiceReference3.TCKisiDurumBilgisi DurumBilgisiField;
        
        private System.Nullable<long> EsTCKimlikNoField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> OncekiYabanciKimlikNoField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        private ServiceReference3.TCKisiTemelBilgisi TemelBilgisiField;
        
        private ServiceReference3.Parametre VeliVasiTurField;
        
        private System.Nullable<bool> VeliVasiVarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneTCKimlikNo
        {
            get
            {
                return this.AnneTCKimlikNoField;
            }
            set
            {
                this.AnneTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AnneUstSoyBulunamadi
        {
            get
            {
                return this.AnneUstSoyBulunamadiField;
            }
            set
            {
                this.AnneUstSoyBulunamadiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaTCKimlikNo
        {
            get
            {
                return this.BabaTCKimlikNoField;
            }
            set
            {
                this.BabaTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> BabaUstSoyBulunamadi
        {
            get
            {
                return this.BabaUstSoyBulunamadiField;
            }
            set
            {
                this.BabaUstSoyBulunamadiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.DogumYerKodField;
            }
            set
            {
                this.DogumYerKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.DurumBilgisiField;
            }
            set
            {
                this.DurumBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsTCKimlikNo
        {
            get
            {
                return this.EsTCKimlikNoField;
            }
            set
            {
                this.EsTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OncekiYabanciKimlikNo
        {
            get
            {
                return this.OncekiYabanciKimlikNoField;
            }
            set
            {
                this.OncekiYabanciKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TCKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.TemelBilgisiField;
            }
            set
            {
                this.TemelBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre VeliVasiTur
        {
            get
            {
                return this.VeliVasiTurField;
            }
            set
            {
                this.VeliVasiTurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> VeliVasiVar
        {
            get
            {
                return this.VeliVasiVarField;
            }
            set
            {
                this.VeliVasiVarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCCuzdanBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCCuzdanBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private System.Nullable<long> CuzdanKayitNoField;
        
        private ServiceReference3.Parametre CuzdanVerilmeNedenField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private string DogumYerField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<int> NoField;
        
        private string SeriField;
        
        private string SoyadField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        private ServiceReference3.Parametre VerildigiIlceField;
        
        private ServiceReference3.TarihBilgisi VerilmeTarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CuzdanKayitNo
        {
            get
            {
                return this.CuzdanKayitNoField;
            }
            set
            {
                this.CuzdanKayitNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre CuzdanVerilmeNeden
        {
            get
            {
                return this.CuzdanVerilmeNedenField;
            }
            set
            {
                this.CuzdanVerilmeNedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> No
        {
            get
            {
                return this.NoField;
            }
            set
            {
                this.NoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seri
        {
            get
            {
                return this.SeriField;
            }
            set
            {
                this.SeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre VerildigiIlce
        {
            get
            {
                return this.VerildigiIlceField;
            }
            set
            {
                this.VerildigiIlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi VerilmeTarih
        {
            get
            {
                return this.VerilmeTarihField;
            }
            set
            {
                this.VerilmeTarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKK", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCKK : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private ServiceReference3.Parametre KanGrubuField;
        
        private string SeriNoField;
        
        private ServiceReference3.TarihBilgisi SonGecerlilikTarihField;
        
        private string SoyadField;
        
        private System.Nullable<bool> SurucuBelgeYuklendiMiField;
        
        private ServiceReference3.TarihBilgisi SurucuBelgeYuklenmeTarihField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        private string VerenMakamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre KanGrubu
        {
            get
            {
                return this.KanGrubuField;
            }
            set
            {
                this.KanGrubuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeriNo
        {
            get
            {
                return this.SeriNoField;
            }
            set
            {
                this.SeriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi SonGecerlilikTarih
        {
            get
            {
                return this.SonGecerlilikTarihField;
            }
            set
            {
                this.SonGecerlilikTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SurucuBelgeYuklendiMi
        {
            get
            {
                return this.SurucuBelgeYuklendiMiField;
            }
            set
            {
                this.SurucuBelgeYuklendiMiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi SurucuBelgeYuklenmeTarih
        {
            get
            {
                return this.SurucuBelgeYuklenmeTarihField;
            }
            set
            {
                this.SurucuBelgeYuklenmeTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerenMakam
        {
            get
            {
                return this.VerenMakamField;
            }
            set
            {
                this.VerenMakamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKKFotoBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCKKFotoBilgisi : object
    {
        
        private byte[] FotografField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotograf
        {
            get
            {
                return this.FotografField;
            }
            set
            {
                this.FotografField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCKisiDurumBilgisi : object
    {
        
        private ServiceReference3.Parametre DurumField;
        
        private ServiceReference3.Parametre MedeniHalField;
        
        private ServiceReference3.TarihBilgisi OlumTarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre MedeniHal
        {
            get
            {
                return this.MedeniHalField;
            }
            set
            {
                this.MedeniHalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi OlumTarih
        {
            get
            {
                return this.OlumTarihField;
            }
            set
            {
                this.OlumTarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCKisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class TCKisiTemelBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private string DogumYerField;
        
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YabanciKisiBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YabanciKisiBilgisi : object
    {
        
        private System.Nullable<long> AnneKimlikNoField;
        
        private System.Nullable<long> BabaKimlikNoField;
        
        private ServiceReference3.Parametre BitisTarihiBelirsizOlmaNedenField;
        
        private ServiceReference3.TarihBilgisi DogumTarihField;
        
        private System.Nullable<int> DogumYerKodField;
        
        private ServiceReference3.YabanciKisiDurumBilgisi DurumBilgisiField;
        
        private System.Nullable<long> EsKimlikNoField;
        
        private System.Nullable<long> GercekKisiKimlikNoField;
        
        private ServiceReference3.Parametre HataBilgisiField;
        
        private System.Nullable<System.DateTime> IzinBaslangicTarihField;
        
        private System.Nullable<System.DateTime> IzinBitisTarihField;
        
        private ServiceReference3.Parametre IzinDuzenlenenIlField;
        
        private string IzinNoField;
        
        private ServiceReference3.Parametre KaynakBirimField;
        
        private System.Nullable<long> KazanilanTCKimlikNoField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference3.TarihBilgisi OlumTarihField;
        
        private ServiceReference3.Parametre StatuField;
        
        private ServiceReference3.YabanciKisiTemelBilgisi TemelBilgisiField;
        
        private ServiceReference3.Parametre UyrukField;
        
        private ServiceReference3.Parametre VeliVasiTurField;
        
        private System.Nullable<bool> VeliVasiVarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneKimlikNo
        {
            get
            {
                return this.AnneKimlikNoField;
            }
            set
            {
                this.AnneKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaKimlikNo
        {
            get
            {
                return this.BabaKimlikNoField;
            }
            set
            {
                this.BabaKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre BitisTarihiBelirsizOlmaNeden
        {
            get
            {
                return this.BitisTarihiBelirsizOlmaNedenField;
            }
            set
            {
                this.BitisTarihiBelirsizOlmaNedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYerKod
        {
            get
            {
                return this.DogumYerKodField;
            }
            set
            {
                this.DogumYerKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YabanciKisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.DurumBilgisiField;
            }
            set
            {
                this.DurumBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsKimlikNo
        {
            get
            {
                return this.EsKimlikNoField;
            }
            set
            {
                this.EsKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> GercekKisiKimlikNo
        {
            get
            {
                return this.GercekKisiKimlikNoField;
            }
            set
            {
                this.GercekKisiKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IzinBaslangicTarih
        {
            get
            {
                return this.IzinBaslangicTarihField;
            }
            set
            {
                this.IzinBaslangicTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IzinBitisTarih
        {
            get
            {
                return this.IzinBitisTarihField;
            }
            set
            {
                this.IzinBitisTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre IzinDuzenlenenIl
        {
            get
            {
                return this.IzinDuzenlenenIlField;
            }
            set
            {
                this.IzinDuzenlenenIlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IzinNo
        {
            get
            {
                return this.IzinNoField;
            }
            set
            {
                this.IzinNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre KaynakBirim
        {
            get
            {
                return this.KaynakBirimField;
            }
            set
            {
                this.KaynakBirimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KazanilanTCKimlikNo
        {
            get
            {
                return this.KazanilanTCKimlikNoField;
            }
            set
            {
                this.KazanilanTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.TarihBilgisi OlumTarih
        {
            get
            {
                return this.OlumTarihField;
            }
            set
            {
                this.OlumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Statu
        {
            get
            {
                return this.StatuField;
            }
            set
            {
                this.StatuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.YabanciKisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.TemelBilgisiField;
            }
            set
            {
                this.TemelBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Uyruk
        {
            get
            {
                return this.UyrukField;
            }
            set
            {
                this.UyrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre VeliVasiTur
        {
            get
            {
                return this.VeliVasiTurField;
            }
            set
            {
                this.VeliVasiTurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> VeliVasiVar
        {
            get
            {
                return this.VeliVasiVarField;
            }
            set
            {
                this.VeliVasiVarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YabanciKisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YabanciKisiDurumBilgisi : object
    {
        
        private ServiceReference3.Parametre DurumField;
        
        private ServiceReference3.Parametre MedeniHalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre MedeniHal
        {
            get
            {
                return this.MedeniHalField;
            }
            set
            {
                this.MedeniHalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YabanciKisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2024/04/01")]
    public partial class YabanciKisiTemelBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference3.Parametre CinsiyetField;
        
        private string DogumYerField;
        
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference3.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2024/04/01", ConfigurationName="ServiceReference3.BilesikKutukSorgulaKimlikNoServis")]
    public interface BilesikKutukSorgulaKimlikNoServis
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2024/04/01/BilesikKutukSorgulaKimlikNoServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2024/04/01/BilesikKutukSorgulaKimlikNoServis/SorgulaRespons" +
            "e")]
        System.Threading.Tasks.Task<ServiceReference3.BilesikKutukBilgileriSonucu> SorgulaAsync(ServiceReference3.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface BilesikKutukSorgulaKimlikNoServisChannel : ServiceReference3.BilesikKutukSorgulaKimlikNoServis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class BilesikKutukSorgulaKimlikNoServisClient : System.ServiceModel.ClientBase<ServiceReference3.BilesikKutukSorgulaKimlikNoServis>, ServiceReference3.BilesikKutukSorgulaKimlikNoServis
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BilesikKutukSorgulaKimlikNoServisClient() : 
                base(BilesikKutukSorgulaKimlikNoServisClient.GetDefaultBinding(), BilesikKutukSorgulaKimlikNoServisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_BilesikKutukSorgulaKimlikNoServis.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServisClient(EndpointConfiguration endpointConfiguration) : 
                base(BilesikKutukSorgulaKimlikNoServisClient.GetBindingForEndpoint(endpointConfiguration), BilesikKutukSorgulaKimlikNoServisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BilesikKutukSorgulaKimlikNoServisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BilesikKutukSorgulaKimlikNoServisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BilesikKutukSorgulaKimlikNoServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference3.BilesikKutukBilgileriSonucu> SorgulaAsync(ServiceReference3.BilesikKutukSorgulaKimlikNoSorguKriteri[] kriterListesi)
        {
            return base.Channel.SorgulaAsync(kriterListesi);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_BilesikKutukSorgulaKimlikNoServis))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TransportSecurityBindingElement userNameOverTransportSecurityBindingElement = System.ServiceModel.Channels.SecurityBindingElement.CreateUserNameOverTransportBindingElement();
                userNameOverTransportSecurityBindingElement.MessageSecurityVersion = System.ServiceModel.MessageSecurityVersion.WSSecurity11WSTrust13WSSecureConversation13WSSecurityPolicy12BasicSecurityProfile10;
                result.Elements.Add(userNameOverTransportSecurityBindingElement);
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_BilesikKutukSorgulaKimlikNoServis))
            {
                return new System.ServiceModel.EndpointAddress("https://kpsv2.nvi.gov.tr/Services/RoutingService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BilesikKutukSorgulaKimlikNoServisClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_BilesikKutukSorgulaKimlikNoServis);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BilesikKutukSorgulaKimlikNoServisClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_BilesikKutukSorgulaKimlikNoServis);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_BilesikKutukSorgulaKimlikNoServis,
        }
    }
}
