//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileAdresSorguKriteri", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileAdresSorguKriteri : object
    {
        
        private System.Nullable<int> DogumAyField;
        
        private System.Nullable<int> DogumGunField;
        
        private System.Nullable<int> DogumYilField;
        
        private System.Nullable<long> KimlikNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumAy
        {
            get
            {
                return this.DogumAyField;
            }
            set
            {
                this.DogumAyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumGun
        {
            get
            {
                return this.DogumGunField;
            }
            set
            {
                this.DogumGunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumYil
        {
            get
            {
                return this.DogumYilField;
            }
            set
            {
                this.DogumYilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgileriSonucu", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileKisiAdresBilgileriSonucu : object
    {
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private ServiceReference2.KimlikNoileKisiAdresBilgileri[] SorguSonucuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileKisiAdresBilgileri[] SorguSonucu
        {
            get
            {
                return this.SorguSonucuField;
            }
            set
            {
                this.SorguSonucuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class Parametre : object
    {
        
        private string AciklamaField;
        
        private System.Nullable<int> KodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgileri", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileKisiAdresBilgileri : object
    {
        
        private ServiceReference2.KimlikNoileKisiAdresBilgisi[] DigerAdresBilgileriField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private System.Nullable<long> KimlikNoField;
        
        private ServiceReference2.KimlikNoileKisiAdresBilgisi YerlesimYeriAdresiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileKisiAdresBilgisi[] DigerAdresBilgileri
        {
            get
            {
                return this.DigerAdresBilgileriField;
            }
            set
            {
                this.DigerAdresBilgileriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KimlikNo
        {
            get
            {
                return this.KimlikNoField;
            }
            set
            {
                this.KimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileKisiAdresBilgisi YerlesimYeriAdresi
        {
            get
            {
                return this.YerlesimYeriAdresiField;
            }
            set
            {
                this.YerlesimYeriAdresiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKisiAdresBilgisi", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileKisiAdresBilgisi : object
    {
        
        private string AcikAdresField;
        
        private System.Nullable<long> AdresNoField;
        
        private ServiceReference2.Parametre AdresTipField;
        
        private ServiceReference2.KimlikNoileBeldeAdresi BeldeAdresiField;
        
        private ServiceReference2.TarihBilgisi BeyanTarihiField;
        
        private System.Nullable<long> BeyandaBulunanKimlikNoField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private ServiceReference2.KimlikNoileIlIlceMerkezi IlIlceMerkezAdresiField;
        
        private ServiceReference2.KimlikNoileKoyAdresi KoyAdresiField;
        
        private System.Nullable<bool> MuvafakatliBeyanField;
        
        private ServiceReference2.Parametre TasinmaNedenField;
        
        private string TasinmaNedenAciklamaField;
        
        private ServiceReference2.TarihBilgisi TasinmaTarihiField;
        
        private ServiceReference2.TarihBilgisi TescilTarihiField;
        
        private ServiceReference2.KimlikNoileYurtDisiAdresi YurtDisiAdresiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcikAdres
        {
            get
            {
                return this.AcikAdresField;
            }
            set
            {
                this.AcikAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AdresNo
        {
            get
            {
                return this.AdresNoField;
            }
            set
            {
                this.AdresNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre AdresTip
        {
            get
            {
                return this.AdresTipField;
            }
            set
            {
                this.AdresTipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileBeldeAdresi BeldeAdresi
        {
            get
            {
                return this.BeldeAdresiField;
            }
            set
            {
                this.BeldeAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.TarihBilgisi BeyanTarihi
        {
            get
            {
                return this.BeyanTarihiField;
            }
            set
            {
                this.BeyanTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BeyandaBulunanKimlikNo
        {
            get
            {
                return this.BeyandaBulunanKimlikNoField;
            }
            set
            {
                this.BeyandaBulunanKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileIlIlceMerkezi IlIlceMerkezAdresi
        {
            get
            {
                return this.IlIlceMerkezAdresiField;
            }
            set
            {
                this.IlIlceMerkezAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileKoyAdresi KoyAdresi
        {
            get
            {
                return this.KoyAdresiField;
            }
            set
            {
                this.KoyAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MuvafakatliBeyan
        {
            get
            {
                return this.MuvafakatliBeyanField;
            }
            set
            {
                this.MuvafakatliBeyanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre TasinmaNeden
        {
            get
            {
                return this.TasinmaNedenField;
            }
            set
            {
                this.TasinmaNedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TasinmaNedenAciklama
        {
            get
            {
                return this.TasinmaNedenAciklamaField;
            }
            set
            {
                this.TasinmaNedenAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.TarihBilgisi TasinmaTarihi
        {
            get
            {
                return this.TasinmaTarihiField;
            }
            set
            {
                this.TasinmaTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.TarihBilgisi TescilTarihi
        {
            get
            {
                return this.TescilTarihiField;
            }
            set
            {
                this.TescilTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.KimlikNoileYurtDisiAdresi YurtDisiAdresi
        {
            get
            {
                return this.YurtDisiAdresiField;
            }
            set
            {
                this.YurtDisiAdresiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileBeldeAdresi", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileBeldeAdresi : object
    {
        
        private ServiceReference2.Parametre BagimsizBolumDurumField;
        
        private ServiceReference2.Parametre BagimsizBolumTipiField;
        
        private string BinaAdaField;
        
        private string BinaBlokAdiField;
        
        private ServiceReference2.Parametre BinaDurumField;
        
        private System.Nullable<long> BinaKoduField;
        
        private System.Nullable<int> BinaNoField;
        
        private ServiceReference2.Parametre BinaNumaratajTipiField;
        
        private string BinaPaftaField;
        
        private string BinaParselField;
        
        private string BinaSiteAdiField;
        
        private ServiceReference2.Parametre BinaYapiTipiField;
        
        private string CsbmField;
        
        private System.Nullable<int> CsbmKoduField;
        
        private string DisKapiNoField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private string IcKapiNoField;
        
        private string IlField;
        
        private System.Nullable<int> IlKoduField;
        
        private string IlceField;
        
        private System.Nullable<int> IlceKoduField;
        
        private string KatNoField;
        
        private string KoyField;
        
        private System.Nullable<long> KoyKayitNoField;
        
        private System.Nullable<long> KoyKoduField;
        
        private string MahalleField;
        
        private System.Nullable<int> MahalleKoduField;
        
        private string TapuBagimsizBolumNoField;
        
        private ServiceReference2.Parametre YapiKullanimAmacField;
        
        private System.Nullable<int> YolAltiKatSayisiField;
        
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumDurum
        {
            get
            {
                return this.BagimsizBolumDurumField;
            }
            set
            {
                this.BagimsizBolumDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumTipi
        {
            get
            {
                return this.BagimsizBolumTipiField;
            }
            set
            {
                this.BagimsizBolumTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda
        {
            get
            {
                return this.BinaAdaField;
            }
            set
            {
                this.BinaAdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi
        {
            get
            {
                return this.BinaBlokAdiField;
            }
            set
            {
                this.BinaBlokAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaDurum
        {
            get
            {
                return this.BinaDurumField;
            }
            set
            {
                this.BinaDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.BinaKoduField;
            }
            set
            {
                this.BinaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.BinaNoField;
            }
            set
            {
                this.BinaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaNumaratajTipi
        {
            get
            {
                return this.BinaNumaratajTipiField;
            }
            set
            {
                this.BinaNumaratajTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta
        {
            get
            {
                return this.BinaPaftaField;
            }
            set
            {
                this.BinaPaftaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel
        {
            get
            {
                return this.BinaParselField;
            }
            set
            {
                this.BinaParselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi
        {
            get
            {
                return this.BinaSiteAdiField;
            }
            set
            {
                this.BinaSiteAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaYapiTipi
        {
            get
            {
                return this.BinaYapiTipiField;
            }
            set
            {
                this.BinaYapiTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm
        {
            get
            {
                return this.CsbmField;
            }
            set
            {
                this.CsbmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.CsbmKoduField;
            }
            set
            {
                this.CsbmKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo
        {
            get
            {
                return this.DisKapiNoField;
            }
            set
            {
                this.DisKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo
        {
            get
            {
                return this.IcKapiNoField;
            }
            set
            {
                this.IcKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.IlKoduField;
            }
            set
            {
                this.IlKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.IlceKoduField;
            }
            set
            {
                this.IlceKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo
        {
            get
            {
                return this.KatNoField;
            }
            set
            {
                this.KatNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy
        {
            get
            {
                return this.KoyField;
            }
            set
            {
                this.KoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo
        {
            get
            {
                return this.KoyKayitNoField;
            }
            set
            {
                this.KoyKayitNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKodu
        {
            get
            {
                return this.KoyKoduField;
            }
            set
            {
                this.KoyKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle
        {
            get
            {
                return this.MahalleField;
            }
            set
            {
                this.MahalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.MahalleKoduField;
            }
            set
            {
                this.MahalleKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.TapuBagimsizBolumNoField;
            }
            set
            {
                this.TapuBagimsizBolumNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre YapiKullanimAmac
        {
            get
            {
                return this.YapiKullanimAmacField;
            }
            set
            {
                this.YapiKullanimAmacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.YolAltiKatSayisiField;
            }
            set
            {
                this.YolAltiKatSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.YolUstuKatSayisiField;
            }
            set
            {
                this.YolUstuKatSayisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class TarihBilgisi : object
    {
        
        private System.Nullable<int> AyField;
        
        private System.Nullable<int> GunField;
        
        private System.Nullable<int> YilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.AyField;
            }
            set
            {
                this.AyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.GunField;
            }
            set
            {
                this.GunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.YilField;
            }
            set
            {
                this.YilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileIlIlceMerkezi", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileIlIlceMerkezi : object
    {
        
        private ServiceReference2.Parametre BagimsizBolumDurumField;
        
        private ServiceReference2.Parametre BagimsizBolumTipiField;
        
        private string BinaAdaField;
        
        private string BinaBlokAdiField;
        
        private ServiceReference2.Parametre BinaDurumField;
        
        private System.Nullable<long> BinaKoduField;
        
        private System.Nullable<int> BinaNoField;
        
        private ServiceReference2.Parametre BinaNumaratajTipiField;
        
        private string BinaPaftaField;
        
        private string BinaParselField;
        
        private string BinaSiteAdiField;
        
        private ServiceReference2.Parametre BinaYapiTipiField;
        
        private string CsbmField;
        
        private System.Nullable<int> CsbmKoduField;
        
        private string DisKapiNoField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private string IcKapiNoField;
        
        private string IlField;
        
        private System.Nullable<int> IlKoduField;
        
        private string IlceField;
        
        private System.Nullable<int> IlceKoduField;
        
        private string KatNoField;
        
        private string MahalleField;
        
        private System.Nullable<int> MahalleKoduField;
        
        private string TapuBagimsizBolumNoField;
        
        private ServiceReference2.Parametre YapiKullanimAmacField;
        
        private System.Nullable<int> YolAltiKatSayisiField;
        
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumDurum
        {
            get
            {
                return this.BagimsizBolumDurumField;
            }
            set
            {
                this.BagimsizBolumDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumTipi
        {
            get
            {
                return this.BagimsizBolumTipiField;
            }
            set
            {
                this.BagimsizBolumTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda
        {
            get
            {
                return this.BinaAdaField;
            }
            set
            {
                this.BinaAdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi
        {
            get
            {
                return this.BinaBlokAdiField;
            }
            set
            {
                this.BinaBlokAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaDurum
        {
            get
            {
                return this.BinaDurumField;
            }
            set
            {
                this.BinaDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.BinaKoduField;
            }
            set
            {
                this.BinaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.BinaNoField;
            }
            set
            {
                this.BinaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaNumaratajTipi
        {
            get
            {
                return this.BinaNumaratajTipiField;
            }
            set
            {
                this.BinaNumaratajTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta
        {
            get
            {
                return this.BinaPaftaField;
            }
            set
            {
                this.BinaPaftaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel
        {
            get
            {
                return this.BinaParselField;
            }
            set
            {
                this.BinaParselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi
        {
            get
            {
                return this.BinaSiteAdiField;
            }
            set
            {
                this.BinaSiteAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaYapiTipi
        {
            get
            {
                return this.BinaYapiTipiField;
            }
            set
            {
                this.BinaYapiTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm
        {
            get
            {
                return this.CsbmField;
            }
            set
            {
                this.CsbmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.CsbmKoduField;
            }
            set
            {
                this.CsbmKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo
        {
            get
            {
                return this.DisKapiNoField;
            }
            set
            {
                this.DisKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo
        {
            get
            {
                return this.IcKapiNoField;
            }
            set
            {
                this.IcKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.IlKoduField;
            }
            set
            {
                this.IlKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.IlceKoduField;
            }
            set
            {
                this.IlceKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo
        {
            get
            {
                return this.KatNoField;
            }
            set
            {
                this.KatNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle
        {
            get
            {
                return this.MahalleField;
            }
            set
            {
                this.MahalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.MahalleKoduField;
            }
            set
            {
                this.MahalleKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.TapuBagimsizBolumNoField;
            }
            set
            {
                this.TapuBagimsizBolumNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre YapiKullanimAmac
        {
            get
            {
                return this.YapiKullanimAmacField;
            }
            set
            {
                this.YapiKullanimAmacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.YolAltiKatSayisiField;
            }
            set
            {
                this.YolAltiKatSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.YolUstuKatSayisiField;
            }
            set
            {
                this.YolUstuKatSayisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileKoyAdresi", Namespace="http://kps.nvi.gov.tr/2023/07/01")]
    public partial class KimlikNoileKoyAdresi : object
    {
        
        private ServiceReference2.Parametre BagimsizBolumDurumField;
        
        private ServiceReference2.Parametre BagimsizBolumTipiField;
        
        private string BinaAdaField;
        
        private string BinaBlokAdiField;
        
        private ServiceReference2.Parametre BinaDurumField;
        
        private System.Nullable<long> BinaKoduField;
        
        private System.Nullable<int> BinaNoField;
        
        private ServiceReference2.Parametre BinaNumaratajTipiField;
        
        private string BinaPaftaField;
        
        private string BinaParselField;
        
        private string BinaSiteAdiField;
        
        private ServiceReference2.Parametre BinaYapiTipiField;
        
        private string CsbmField;
        
        private System.Nullable<int> CsbmKoduField;
        
        private string DisKapiNoField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private string IcKapiNoField;
        
        private string IlField;
        
        private System.Nullable<int> IlKoduField;
        
        private string IlceField;
        
        private System.Nullable<int> IlceKoduField;
        
        private string KatNoField;
        
        private string KoyField;
        
        private System.Nullable<long> KoyKayitNoField;
        
        private System.Nullable<long> KoyKoduField;
        
        private string MahalleField;
        
        private System.Nullable<int> MahalleKoduField;
        
        private string TapuBagimsizBolumNoField;
        
        private ServiceReference2.Parametre YapiKullanimAmacField;
        
        private System.Nullable<int> YolAltiKatSayisiField;
        
        private System.Nullable<int> YolUstuKatSayisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumDurum
        {
            get
            {
                return this.BagimsizBolumDurumField;
            }
            set
            {
                this.BagimsizBolumDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BagimsizBolumTipi
        {
            get
            {
                return this.BagimsizBolumTipiField;
            }
            set
            {
                this.BagimsizBolumTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaAda
        {
            get
            {
                return this.BinaAdaField;
            }
            set
            {
                this.BinaAdaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaBlokAdi
        {
            get
            {
                return this.BinaBlokAdiField;
            }
            set
            {
                this.BinaBlokAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaDurum
        {
            get
            {
                return this.BinaDurumField;
            }
            set
            {
                this.BinaDurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BinaKodu
        {
            get
            {
                return this.BinaKoduField;
            }
            set
            {
                this.BinaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BinaNo
        {
            get
            {
                return this.BinaNoField;
            }
            set
            {
                this.BinaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaNumaratajTipi
        {
            get
            {
                return this.BinaNumaratajTipiField;
            }
            set
            {
                this.BinaNumaratajTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaPafta
        {
            get
            {
                return this.BinaPaftaField;
            }
            set
            {
                this.BinaPaftaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaParsel
        {
            get
            {
                return this.BinaParselField;
            }
            set
            {
                this.BinaParselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaSiteAdi
        {
            get
            {
                return this.BinaSiteAdiField;
            }
            set
            {
                this.BinaSiteAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre BinaYapiTipi
        {
            get
            {
                return this.BinaYapiTipiField;
            }
            set
            {
                this.BinaYapiTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Csbm
        {
            get
            {
                return this.CsbmField;
            }
            set
            {
                this.CsbmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CsbmKodu
        {
            get
            {
                return this.CsbmKoduField;
            }
            set
            {
                this.CsbmKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisKapiNo
        {
            get
            {
                return this.DisKapiNoField;
            }
            set
            {
                this.DisKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcKapiNo
        {
            get
            {
                return this.IcKapiNoField;
            }
            set
            {
                this.IcKapiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlKodu
        {
            get
            {
                return this.IlKoduField;
            }
            set
            {
                this.IlKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IlceKodu
        {
            get
            {
                return this.IlceKoduField;
            }
            set
            {
                this.IlceKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KatNo
        {
            get
            {
                return this.KatNoField;
            }
            set
            {
                this.KatNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koy
        {
            get
            {
                return this.KoyField;
            }
            set
            {
                this.KoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKayitNo
        {
            get
            {
                return this.KoyKayitNoField;
            }
            set
            {
                this.KoyKayitNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> KoyKodu
        {
            get
            {
                return this.KoyKoduField;
            }
            set
            {
                this.KoyKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mahalle
        {
            get
            {
                return this.MahalleField;
            }
            set
            {
                this.MahalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MahalleKodu
        {
            get
            {
                return this.MahalleKoduField;
            }
            set
            {
                this.MahalleKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TapuBagimsizBolumNo
        {
            get
            {
                return this.TapuBagimsizBolumNoField;
            }
            set
            {
                this.TapuBagimsizBolumNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre YapiKullanimAmac
        {
            get
            {
                return this.YapiKullanimAmacField;
            }
            set
            {
                this.YapiKullanimAmacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolAltiKatSayisi
        {
            get
            {
                return this.YolAltiKatSayisiField;
            }
            set
            {
                this.YolAltiKatSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YolUstuKatSayisi
        {
            get
            {
                return this.YolUstuKatSayisiField;
            }
            set
            {
                this.YolUstuKatSayisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KimlikNoileYurtDisiAdresi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KimlikNoileYurtDisiAdresi : object
    {
        
        private System.Nullable<System.DateTime> DisTemsDuzeltmeBeyanTarihField;
        
        private System.Nullable<System.DateTime> DisTemsDuzeltmeKararTarihField;
        
        private ServiceReference2.Parametre DisTemsDuzeltmeNedenField;
        
        private ServiceReference2.Parametre DisTemsilcilikField;
        
        private ServiceReference2.Parametre HataBilgisiField;
        
        private string YabanciAdresField;
        
        private string YabanciSehirField;
        
        private ServiceReference2.Parametre YabanciUlkeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeBeyanTarih
        {
            get
            {
                return this.DisTemsDuzeltmeBeyanTarihField;
            }
            set
            {
                this.DisTemsDuzeltmeBeyanTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DisTemsDuzeltmeKararTarih
        {
            get
            {
                return this.DisTemsDuzeltmeKararTarihField;
            }
            set
            {
                this.DisTemsDuzeltmeKararTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre DisTemsDuzeltmeNeden
        {
            get
            {
                return this.DisTemsDuzeltmeNedenField;
            }
            set
            {
                this.DisTemsDuzeltmeNedenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre DisTemsilcilik
        {
            get
            {
                return this.DisTemsilcilikField;
            }
            set
            {
                this.DisTemsilcilikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciAdres
        {
            get
            {
                return this.YabanciAdresField;
            }
            set
            {
                this.YabanciAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YabanciSehir
        {
            get
            {
                return this.YabanciSehirField;
            }
            set
            {
                this.YabanciSehirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.Parametre YabanciUlke
        {
            get
            {
                return this.YabanciUlkeField;
            }
            set
            {
                this.YabanciUlkeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2023/07/01", ConfigurationName="ServiceReference2.KimlikNoSorgulaAdresServis")]
    public interface KimlikNoSorgulaAdresServis
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2023/07/01/KimlikNoSorgulaAdresServis/Sorgula", ReplyAction="http://kps.nvi.gov.tr/2023/07/01/KimlikNoSorgulaAdresServis/SorgulaResponse")]
        System.Threading.Tasks.Task<ServiceReference2.KimlikNoileKisiAdresBilgileriSonucu> SorgulaAsync(ServiceReference2.KimlikNoileAdresSorguKriteri[] kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface KimlikNoSorgulaAdresServisChannel : ServiceReference2.KimlikNoSorgulaAdresServis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class KimlikNoSorgulaAdresServisClient : System.ServiceModel.ClientBase<ServiceReference2.KimlikNoSorgulaAdresServis>, ServiceReference2.KimlikNoSorgulaAdresServis
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KimlikNoSorgulaAdresServisClient() : 
                base(KimlikNoSorgulaAdresServisClient.GetDefaultBinding(), KimlikNoSorgulaAdresServisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_KimlikNoSorgulaAdresServis.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimlikNoSorgulaAdresServisClient(EndpointConfiguration endpointConfiguration) : 
                base(KimlikNoSorgulaAdresServisClient.GetBindingForEndpoint(endpointConfiguration), KimlikNoSorgulaAdresServisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimlikNoSorgulaAdresServisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KimlikNoSorgulaAdresServisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimlikNoSorgulaAdresServisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KimlikNoSorgulaAdresServisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimlikNoSorgulaAdresServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.KimlikNoileKisiAdresBilgileriSonucu> SorgulaAsync(ServiceReference2.KimlikNoileAdresSorguKriteri[] kriterListesi)
        {
            return base.Channel.SorgulaAsync(kriterListesi);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_KimlikNoSorgulaAdresServis))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_KimlikNoSorgulaAdresServis))
            {
                return new System.ServiceModel.EndpointAddress("https://kpsv2.nvi.gov.tr/Services/RoutingService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KimlikNoSorgulaAdresServisClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_KimlikNoSorgulaAdresServis);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KimlikNoSorgulaAdresServisClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_KimlikNoSorgulaAdresServis);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_KimlikNoSorgulaAdresServis,
        }
    }
}
