//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiSorgulaKisiBilgiSorguKriteri", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiSorgulaKisiBilgiSorguKriteri : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private System.Nullable<ServiceReference1.CstCinsiyet> CinsiyetField;
        
        private System.Nullable<int> DogumTarihAyField;
        
        private System.Nullable<int> DogumTarihGunField;
        
        private System.Nullable<int> DogumTarihYilField;
        
        private string DogumYerField;
        
        private System.Nullable<ServiceReference1.KisiSorguMode> KisiSorguModuField;
        
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference1.CstCinsiyet> Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumTarihAy
        {
            get
            {
                return this.DogumTarihAyField;
            }
            set
            {
                this.DogumTarihAyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumTarihGun
        {
            get
            {
                return this.DogumTarihGunField;
            }
            set
            {
                this.DogumTarihGunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DogumTarihYil
        {
            get
            {
                return this.DogumTarihYilField;
            }
            set
            {
                this.DogumTarihYilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ServiceReference1.KisiSorguMode> KisiSorguModu
        {
            get
            {
                return this.KisiSorguModuField;
            }
            set
            {
                this.KisiSorguModuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CstCinsiyet", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public enum CstCinsiyet : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bilinmeyen = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erkek = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kadin = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiSorguMode", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public enum KisiSorguMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SoyadBos = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BabaBos = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiBilgilerindenKisiBilgisiSonucu", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiBilgilerindenKisiBilgisiSonucu : object
    {
        
        private ServiceReference1.Parametre HataBilgisiField;
        
        private ServiceReference1.KisiBilgilerindenKisiBilgisi[] SorguSonucuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.KisiBilgilerindenKisiBilgisi[] SorguSonucu
        {
            get
            {
                return this.SorguSonucuField;
            }
            set
            {
                this.SorguSonucuField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametre", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class Parametre : object
    {
        
        private string AciklamaField;
        
        private System.Nullable<int> KodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kod
        {
            get
            {
                return this.KodField;
            }
            set
            {
                this.KodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiBilgilerindenKisiBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiBilgilerindenKisiBilgisi : object
    {
        
        private System.Nullable<long> AnneTCKimlikNoField;
        
        private System.Nullable<long> BabaTCKimlikNoField;
        
        private ServiceReference1.KisiDurumBilgisi DurumBilgisiField;
        
        private System.Nullable<long> EsTCKimlikNoField;
        
        private ServiceReference1.Parametre HataBilgisiField;
        
        private ServiceReference1.KisiKayitYeriBilgisi KayitYeriBilgisiField;
        
        private System.Nullable<long> TCKimlikNoField;
        
        private ServiceReference1.KisiTemelBilgisi TemelBilgisiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AnneTCKimlikNo
        {
            get
            {
                return this.AnneTCKimlikNoField;
            }
            set
            {
                this.AnneTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BabaTCKimlikNo
        {
            get
            {
                return this.BabaTCKimlikNoField;
            }
            set
            {
                this.BabaTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.KisiDurumBilgisi DurumBilgisi
        {
            get
            {
                return this.DurumBilgisiField;
            }
            set
            {
                this.DurumBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> EsTCKimlikNo
        {
            get
            {
                return this.EsTCKimlikNoField;
            }
            set
            {
                this.EsTCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre HataBilgisi
        {
            get
            {
                return this.HataBilgisiField;
            }
            set
            {
                this.HataBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.KisiKayitYeriBilgisi KayitYeriBilgisi
        {
            get
            {
                return this.KayitYeriBilgisiField;
            }
            set
            {
                this.KayitYeriBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TCKimlikNo
        {
            get
            {
                return this.TCKimlikNoField;
            }
            set
            {
                this.TCKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.KisiTemelBilgisi TemelBilgisi
        {
            get
            {
                return this.TemelBilgisiField;
            }
            set
            {
                this.TemelBilgisiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiDurumBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiDurumBilgisi : object
    {
        
        private ServiceReference1.Parametre DinField;
        
        private ServiceReference1.Parametre DurumField;
        
        private ServiceReference1.Parametre MedeniHalField;
        
        private ServiceReference1.TarihBilgisi OlumTarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Din
        {
            get
            {
                return this.DinField;
            }
            set
            {
                this.DinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Durum
        {
            get
            {
                return this.DurumField;
            }
            set
            {
                this.DurumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre MedeniHal
        {
            get
            {
                return this.MedeniHalField;
            }
            set
            {
                this.MedeniHalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TarihBilgisi OlumTarih
        {
            get
            {
                return this.OlumTarihField;
            }
            set
            {
                this.OlumTarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiKayitYeriBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiKayitYeriBilgisi : object
    {
        
        private System.Nullable<int> AileSiraNoField;
        
        private System.Nullable<int> BireySiraNoField;
        
        private ServiceReference1.Parametre CiltField;
        
        private ServiceReference1.Parametre IlField;
        
        private ServiceReference1.Parametre IlceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AileSiraNo
        {
            get
            {
                return this.AileSiraNoField;
            }
            set
            {
                this.AileSiraNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BireySiraNo
        {
            get
            {
                return this.BireySiraNoField;
            }
            set
            {
                this.BireySiraNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Cilt
        {
            get
            {
                return this.CiltField;
            }
            set
            {
                this.CiltField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Il
        {
            get
            {
                return this.IlField;
            }
            set
            {
                this.IlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Ilce
        {
            get
            {
                return this.IlceField;
            }
            set
            {
                this.IlceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KisiTemelBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class KisiTemelBilgisi : object
    {
        
        private string AdField;
        
        private string AnneAdField;
        
        private string BabaAdField;
        
        private ServiceReference1.Parametre CinsiyetField;
        
        private ServiceReference1.TarihBilgisi DogumTarihField;
        
        private string DogumYerField;
        
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad
        {
            get
            {
                return this.AdField;
            }
            set
            {
                this.AdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnneAd
        {
            get
            {
                return this.AnneAdField;
            }
            set
            {
                this.AnneAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BabaAd
        {
            get
            {
                return this.BabaAdField;
            }
            set
            {
                this.BabaAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Parametre Cinsiyet
        {
            get
            {
                return this.CinsiyetField;
            }
            set
            {
                this.CinsiyetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TarihBilgisi DogumTarih
        {
            get
            {
                return this.DogumTarihField;
            }
            set
            {
                this.DogumTarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DogumYer
        {
            get
            {
                return this.DogumYerField;
            }
            set
            {
                this.DogumYerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad
        {
            get
            {
                return this.SoyadField;
            }
            set
            {
                this.SoyadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TarihBilgisi", Namespace="http://kps.nvi.gov.tr/2011/01/01")]
    public partial class TarihBilgisi : object
    {
        
        private System.Nullable<int> AyField;
        
        private System.Nullable<int> GunField;
        
        private System.Nullable<int> YilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ay
        {
            get
            {
                return this.AyField;
            }
            set
            {
                this.AyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gun
        {
            get
            {
                return this.GunField;
            }
            set
            {
                this.GunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Yil
        {
            get
            {
                return this.YilField;
            }
            set
            {
                this.YilField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kps.nvi.gov.tr/2011/01/01", ConfigurationName="ServiceReference1.KisiSorgulaKisiBilgiServis")]
    public interface KisiSorgulaKisiBilgiServis
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kps.nvi.gov.tr/2011/01/01/KisiSorgulaKisiBilgiServis/ListeleCoklu", ReplyAction="http://kps.nvi.gov.tr/2011/01/01/KisiSorgulaKisiBilgiServis/ListeleCokluResponse")]
        System.Threading.Tasks.Task<ServiceReference1.KisiBilgilerindenKisiBilgisiSonucu> ListeleCokluAsync(ServiceReference1.KisiSorgulaKisiBilgiSorguKriteri[] kriterListesi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface KisiSorgulaKisiBilgiServisChannel : ServiceReference1.KisiSorgulaKisiBilgiServis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class KisiSorgulaKisiBilgiServisClient : System.ServiceModel.ClientBase<ServiceReference1.KisiSorgulaKisiBilgiServis>, ServiceReference1.KisiSorgulaKisiBilgiServis
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KisiSorgulaKisiBilgiServisClient() : 
                base(KisiSorgulaKisiBilgiServisClient.GetDefaultBinding(), KisiSorgulaKisiBilgiServisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_KisiSorgulaKisiBilgiServis.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KisiSorgulaKisiBilgiServisClient(EndpointConfiguration endpointConfiguration) : 
                base(KisiSorgulaKisiBilgiServisClient.GetBindingForEndpoint(endpointConfiguration), KisiSorgulaKisiBilgiServisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KisiSorgulaKisiBilgiServisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KisiSorgulaKisiBilgiServisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KisiSorgulaKisiBilgiServisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KisiSorgulaKisiBilgiServisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KisiSorgulaKisiBilgiServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.KisiBilgilerindenKisiBilgisiSonucu> ListeleCokluAsync(ServiceReference1.KisiSorgulaKisiBilgiSorguKriteri[] kriterListesi)
        {
            return base.Channel.ListeleCokluAsync(kriterListesi);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_KisiSorgulaKisiBilgiServis))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TransportSecurityBindingElement userNameOverTransportSecurityBindingElement = System.ServiceModel.Channels.SecurityBindingElement.CreateUserNameOverTransportBindingElement();
                userNameOverTransportSecurityBindingElement.MessageSecurityVersion = System.ServiceModel.MessageSecurityVersion.WSSecurity11WSTrust13WSSecureConversation13WSSecurityPolicy12BasicSecurityProfile10;
                result.Elements.Add(userNameOverTransportSecurityBindingElement);
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_KisiSorgulaKisiBilgiServis))
            {
                return new System.ServiceModel.EndpointAddress("https://kpsv2.nvi.gov.tr/Services/RoutingService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KisiSorgulaKisiBilgiServisClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_KisiSorgulaKisiBilgiServis);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KisiSorgulaKisiBilgiServisClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_KisiSorgulaKisiBilgiServis);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_KisiSorgulaKisiBilgiServis,
        }
    }
}
